# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1570, 702)
        self.video = QtWidgets.QLabel(main)
        self.video.setGeometry(QtCore.QRect(40, 170, 721, 441))
        self.video.setStyleSheet("font: 14pt \"黑体\";")
        self.video.setAlignment(QtCore.Qt.AlignCenter)
        self.video.setObjectName("video")
        self.label_2 = QtWidgets.QLabel(main)
        self.label_2.setGeometry(QtCore.QRect(570, 20, 451, 51))
        self.label_2.setStyleSheet("font: 16pt \"方正小标宋简体\";")
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(main)
        self.textBrowser.setGeometry(QtCore.QRect(820, 170, 721, 441))
        self.textBrowser.setStyleSheet("font: 12pt \"黑体\";")
        self.textBrowser.setObjectName("textBrowser")
        self.cameraButton = QtWidgets.QPushButton(main)
        self.cameraButton.setGeometry(QtCore.QRect(430, 630, 141, 51))
        self.cameraButton.setStyleSheet("font: 11pt \"黑体\";")
        self.cameraButton.setObjectName("cameraButton")
        self.grabButton = QtWidgets.QPushButton(main)
        self.grabButton.setGeometry(QtCore.QRect(20, 10, 71, 41))
        self.grabButton.setStyleSheet("font: 11pt \"黑体\";")
        self.grabButton.setObjectName("grabButton")
        self.resetButton = QtWidgets.QPushButton(main)
        self.resetButton.setGeometry(QtCore.QRect(240, 630, 141, 51))
        self.resetButton.setStyleSheet("font: 11pt \"黑体\";")
        self.resetButton.setObjectName("resetButton")
        self.emgButton = QtWidgets.QPushButton(main)
        self.emgButton.setGeometry(QtCore.QRect(1110, 630, 141, 51))
        self.emgButton.setStyleSheet("font: 11pt \"黑体\";")
        self.emgButton.setObjectName("emgButton")
        self.line = QtWidgets.QFrame(main)
        self.line.setGeometry(QtCore.QRect(780, 110, 20, 551))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(main)
        self.label.setGeometry(QtCore.QRect(310, 100, 181, 71))
        self.label.setStyleSheet("font: 16pt \"新宋体\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(main)
        self.label_3.setGeometry(QtCore.QRect(1080, 100, 201, 71))
        self.label_3.setStyleSheet("font: 16pt \"新宋体\";")
        self.label_3.setObjectName("label_3")
        self.forwardButton = QtWidgets.QPushButton(main)
        self.forwardButton.setGeometry(QtCore.QRect(110, 10, 81, 41))
        self.forwardButton.setStyleSheet("font: 11pt \"黑体\";")
        self.forwardButton.setObjectName("forwardButton")
        self.leftButton = QtWidgets.QPushButton(main)
        self.leftButton.setGeometry(QtCore.QRect(210, 10, 81, 41))
        self.leftButton.setStyleSheet("font: 11pt \"黑体\";")
        self.leftButton.setObjectName("leftButton")
        self.rightButton = QtWidgets.QPushButton(main)
        self.rightButton.setGeometry(QtCore.QRect(310, 10, 81, 41))
        self.rightButton.setStyleSheet("font: 11pt \"黑体\";")
        self.rightButton.setObjectName("rightButton")
        self.comboBox = QtWidgets.QComboBox(main)
        self.comboBox.setGeometry(QtCore.QRect(1390, 30, 151, 41))
        self.comboBox.setStyleSheet("font: 12pt \"黑体\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(main)
        self.label_4.setGeometry(QtCore.QRect(1320, 30, 71, 41))
        self.label_4.setStyleSheet("font: 14pt \"黑体\";")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Dialog"))
        self.video.setText(_translate("main", "无视频信号"))
        self.label_2.setText(_translate("main", "基于肌电信号的残疾人智能辅助系统"))
        self.textBrowser.setHtml(_translate("main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.cameraButton.setText(_translate("main", "打开摄像头"))
        self.grabButton.setText(_translate("main", "抓取"))
        self.resetButton.setText(_translate("main", "强制停止"))
        self.emgButton.setText(_translate("main", "开启肌电采集"))
        self.label.setText(_translate("main", "抓物小车控制"))
        self.label_3.setText(_translate("main", "肌电下位机控制"))
        self.forwardButton.setText(_translate("main", "前进"))
        self.leftButton.setText(_translate("main", "左转"))
        self.rightButton.setText(_translate("main", "右转"))
        self.comboBox.setItemText(0, _translate("main", "室内自动工作"))
        self.comboBox.setItemText(1, _translate("main", "室外手动驾驶"))
        self.label_4.setText(_translate("main", "模式:"))
